version: '3.8'

services:
  fastapi:
    container_name: fastapi_autodistill_project
    build: ./fastapi
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - ./fastapi:/app/fastapi  
    restart: unless-stopped
    env_file:
        - .env
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      - minio
    networks:
      - mynetwork

  streamlit:
    container_name: streamlit_autodistill_project
    build: ./streamlit
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - .:/app  
    restart: unless-stopped
    env_file:
        - .env
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    networks:
      - mynetwork
      
  minio:
    image: "minio/minio:RELEASE.2021-10-13T00-23-17Z"
    container_name: minio_autodistill_project
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3



volumes:
  minio_data:
  minio_config:

networks:
  mynetwork:
    driver: bridge